graasp/graasp-library

.gitignore

chore: add package lock to gitignore

---

README.md

chore: made two minor language edits to README.md

---

package.json
src/api/collection.js
src/client.js
src/client/components/CollectionProvider.js
src/client/components/collection/Collection.js
src/server.js
yarn.lock

feat: fetch data and provide to client with context

---

.dockerignore
Dockerfile
src/client/components/common/GraaspQuill.js

I am not confortable with Docker, I tried but currently I have the following error 
```
> Started on port 3000
/node_modules/quill/dist/quill.js:7661
var elem = document.createElement('div');
^
ReferenceError: document is not defined
```
Anyone can use this branch to correct it!

feat: docker

---

src/client/components/App.test.js
src/client/components/CollectionProvider.js
src/client/components/collection/Collection.js
src/client/components/collection/CollectionCard.js
src/client/components/collection/CollectionsGrid.js
src/client/components/collection/Comment.js
src/client/components/collection/SimilarCollectionBadges.js
src/client/components/collection/SimilarCollections.js
src/client/components/collection/Summary.js
src/client/components/home/Home.js
src/client/config/routes.js
src/server.js

feat: display all collections on home

---

src/client/components/layout/Header.js

fixed clicking on home
fixes #38

fix: clicking on home should go to home

---

package.json
src/api/collection.js
src/api/endpoints.js
src/api/env.js
src/client.js
src/client/components/App.js
src/client/components/Root.js
src/client/components/collection/Collection.js
src/client/components/collection/CollectionCard.js
src/client/components/common/Error.js
src/client/components/layout/Footer.js
src/client/config/constants.js
src/client/config/errors.js
src/client/config/routes.js
src/middlewares.js
src/render.js
src/server.js
yarn.lock

I'm not familiar with Sentry so I might have not set it up properly. Please play around and check if everything is fine/errors are caught properly. 
close #49
close #36
close #34
close #29

feat: set up sentry, google analytics, handle errors

---

src/client/components/collection/Collection.js
src/client/components/collection/Comment.js
src/client/langs/en.json
src/client/langs/fr.json

fix: default comment author to guest

---

src/api/endpoints.js

refactor: use cloud and preview page when viewing spaces

---

next.config.js
package.json
src/components/collection/Authorship.js
src/components/collection/CollectionCard.js
src/components/collection/Item.js
src/components/collection/Summary.js
src/components/common/CardMediaComponent.js
src/components/layout/UserHeader.js
src/config/constants.js
src/config/env.js
src/config/theme.js
yarn.lock

close #78 
This still need to be tested.

feat: display thumbnails

---

src/components/collection/CollectionCard.js
src/components/collection/CopyLinkButton.js
src/components/collection/Item.js
src/config/notifier.js
src/utils/clipboard.js

feat: add copy link button

---

src/components/collection/Collection.js
src/components/collection/Summary.js
src/components/home/AllCollections.js

close #96 
fix the problem that item card width varies
close #98
Display user-defined tags on item summary

fix: fix item card width

---

src/components/collection/Collection.js

I forget to commit this minor fix in previous PR so I just add it

fix: minor fix

---

src/components/collection/Summary.js
src/components/home/Home.js
src/components/home/Search.js
src/config/constants.js
src/langs/en.json
yarn.lock

close #104 
- new layout for search (see pic in next comment)
- the author button is also enabled now 
- the old local search is also replaced with the new search with backend and directly search within DB

feat: add search box & buttons

---

package.json
src/components/home/Home.js
yarn.lock

refactor the handle search keywords functions, move the preprocess to backend
close #114

fix: optimize keyword formatting to backend

---

src/components/home/AllCollections.js
src/components/home/LevelCollectionsPage.js
src/components/home/Search.js
src/config/constants.js
src/langs/en.json

enable multiselect for category menu
add skeleton when loading the category list
close #94 
close #85

feat: category multiselect

---

src/components/collection/DownloadButton.js

fix: update the downloadItem mutation call

---

src/components/collection/CollectionsGrid.js
src/components/home/AllCollections.js
src/components/home/LevelCollectionsPage.js
src/config/constants.js
src/config/cssStyles.js

146/fix UI

---

cypress/fixtures/categories.js
cypress/fixtures/items.js
cypress/integration/collection/categories.spec.js
src/components/collection/Summary.js
src/components/home/AllCollections.js
src/components/home/CategorySelection.js
src/components/home/LevelCollectionsPage.js
src/config/constants.js
src/config/selectors.js
src/config/theme.js

feat: add langauge category

---

cypress/fixtures/items.js
cypress/integration/collection/summary.spec.js
src/components/collection/Authorship.js
src/components/collection/Contributors.js
src/components/collection/Summary.js

feat: display co-editors

---

cypress/integration/collection/categories.spec.js
cypress/integration/myLists/myFavorites.spec.js
package.json
src/components/QueryClientContext.js
src/components/collection/Authorship.js
src/components/collection/Collection.js
src/components/collection/CollectionCard.js
src/components/collection/CopyButton.js
src/components/collection/Summary.js
src/components/common/CardMediaComponent.js
src/components/home/CreateButton.js
src/components/home/MyFavorites.js
src/components/home/MyLikes.js
src/components/home/MyPublishments.js
src/components/layout/Header.js
src/components/layout/UserHeader.js
src/config/queryClient.js
src/utils/collections.js
yarn.lock

176 immutable

---

.github/workflows/sentry.yml

refactor: fix sentry workflow

---

src/components/collection/TreeModal.js

fix: copy dialog modal should not show expanded tree

---

src/components/common/TranslationWrapper.tsx
src/components/common/Wrapper.js
src/components/home/CreateButton.tsx
src/components/layout/Footer.js
src/config/constants.ts
yarn.lock

feat: use member's lang when signed in

---

.github/workflows/cdelivery-ecs-library-caller.yml
.github/workflows/cdeployment-ecs-library-caller.yml
.github/workflows/cintegration-ecs-library-caller.yml

ci: cancel stale deployment workflow runs

---

pages/api/status.ts

feat: add healthcheck endpoint

---

src/components/collection/ChildrenCard.tsx
src/components/collection/CopyButton.js
src/components/collection/CopyLinkButton.js

fix: display children card actions below item

---

cypress/e2e/home/search.cy.ts
src/components/collection/CollectionCard.tsx
src/components/collection/CollectionsGrid.tsx
src/components/pages/AllCollections.tsx
src/config/selectors.ts
src/utils/types.ts

fix: handle serch error without crash

---

src/components/common/BackButton.tsx
src/components/search/SearchResults.tsx
yarn.lock

This PR fixes #391 by:
- opening the search results of the main page in the same tab
- closing the tab when clicking on back in the colection page when there is no history

fix(navigation): open search in current tab and close tab if there is no history on back button

---

src/components/collection/summary/SummaryHeader.tsx
src/components/layout/HomeHeader.tsx

fix: add clickable tags in collection header

---

src/components/common/HeaderNavigation.tsx

fix: path to analytics items

---

.github/workflows/deploy-dev.yml

TO MERGE ONLY AFTER RELEASING THAT https://github.com/graasp/graasp-deploy/pull/241

fix: remove branch from deploy dev workflow

---

app/collections/[id]/page.tsx
src/components/common/Wrapper.tsx
src/components/layout/HomeHeader.tsx

fix: set white background in collection view

---

src/components/collection/CollectionsGrid.tsx
src/components/collection/ItemCollection.tsx
src/components/pages/Home.tsx

The result could be better, but we will change cards anyway, so let's have this first simple skeleton.
close #688

feat: show skeleton on loading on home page

---

.gitignore
.storybook/main.ts
.storybook/preview.ts
package.json
src/components/collection/ContentDescription.tsx
src/components/common/CollapsibleText/CollapsibleText.stories.tsx
src/components/common/CollapsibleText/CollapsibleText.tsx
src/components/common/ShowLessAndMoreContent.tsx
yarn.lock

Add storybook in library, since we won't be using graasp-ui anymore. Instead we will get graasp-ui from /client.
Whenever possible, library components should stay in library, like the new card layout.

feat: add storybook and collapsible text

---

README.md
src/config/env.ts

In this PR I update the docs to make the usage clearer.

fix: update docs

---

messages/ar.json
messages/de.json
messages/en.json
messages/es.json

fix: remove br tag in translations

---

package.json
src/components/Header.tsx

In this PR:
- fix #790
https://github.com/user-attachments/assets/5d3a3c56-567f-4b73-9647-6434feb72f71

fix: add active link styling on header

---

src/components/collection/collectionCard/CollectionCard.tsx

fix: use sort instead of toSorted for compatibility

---

src/components/collection/UnpublishedItemAlert.tsx
src/components/header/UserAvatar.tsx
src/openapi/client/@tanstack/react-query.gen.ts
src/openapi/client/sdk.gen.ts
src/openapi/client/types.gen.ts

merge after this https://github.com/graasp/graasp/pull/1944

feat: update client, fix sign out
